export interface GCP {
  id: number;
  number: string;
  type: string;
  barangay: string;
  status: string;
  latitude: number;
  longitude: number;
  description: string;
  remarks: string;
  condition: string;
  // lastVerified: string; // ISO date string format
  imageUrl: string;
}
export const gcpData: GCP[] = [
  {
    id: 1,
    number: 'BBM 36',
    type: 'BBM',
    barangay: 'Iraya and Poblacion',
    status: 'Disturbed',
    latitude: 13.190061,
    longitude: 123.601767,
    description: 'Near Niones Madrid Dental Clinic',
    remarks: 'Visible yet disturbed',
    condition: 'The GCP is not intact on the ground and can be easily moved',
    imageUrl: '/images/Picture1.jpg',
  },
  {
    id: 2,
    number: 'BLLM UNKNOWN',
    type: 'BLLM',
    barangay: 'Inamnan Pequeño',
    status: 'Unidentified',
    latitude: 13.185,
    longitude: 123.599167,
    description: 'INAMNAN PEQUEÑO BRGY HALL',
    remarks: 'Unidentified',
    condition:
      'The GCP remains intact as of December, 2024. The control number of the GCP cannot be identified',
    imageUrl: '/images/Picture2.jpg',
  },
  {
    id: 3,
    number: 'GCP UNKNOWN',
    type: 'Unknown',
    barangay: 'Calzada',
    status: 'Unidentified',
    latitude: 13.190678,
    longitude: 123.594847,
    description: 'Near the Catholic Cemetery in Calzada',
    remarks: 'Unidentified',
    condition: 'Unknown GCP',
    imageUrl: '/images/Picture3.jpg',
  },
  {
    id: 4,
    number: 'BLLM UNKNOWN',
    type: 'BLLM',
    barangay: 'Inamnan Grande',
    status: 'Disturbed',
    latitude: 13.187006,
    longitude: 123.595686,
    description: 'Brgy Inamnan Grande',
    remarks: 'Disturbed',
    condition: 'Intact on the ground but control number cannot be identified',
    imageUrl: '/images/Picture4.jpg',
  },
  {
    id: 5,
    number: 'BLLM 1',
    type: 'BLLM',
    barangay: 'Poblacion',
    status: 'Intact',
    latitude: 13.191561,
    longitude: 123.599164,
    description: 'Near Guinobatan Municipal Hall',
    remarks: 'Intact',
    condition: 'Intact on the ground. The control number is identifiable',
    imageUrl: '/images/Picture5.jpg',
  },
  {
    id: 6,
    number: 'BLLM UNKNOWN',
    type: 'BLLM',
    barangay: 'Iraya',
    status: 'Unidentified',
    latitude: 13.193889,
    longitude: 123.596389,
    description: 'In front of Funeral Chapel',
    remarks: 'Unidentified',
    condition: 'Intact on the ground but control number cannot be identified',
    imageUrl: '/images/Picture6.jpg',
  },
  {
    id: 7,
    number: 'BLLM 1A',
    type: 'BLLM',
    barangay: 'Centro Guinobatan',
    status: 'Intact',
    latitude: 13.191086,
    longitude: 123.600594,
    description: 'Near the light post near the entrance of the Catholic Church',
    remarks: 'Intact',
    condition: 'Intact but with missing description on top of the GCP',
    imageUrl: '/images/Picture7.jpg',
  },
  {
    id: 8,
    number: 'BLLM 7X',
    type: 'BLLM',
    barangay: 'Calzada',
    status: 'Unidentified',
    latitude: 13.189375,
    longitude: 123.595797,
    description: 'Near Calzada Barangay Hall',
    remarks: 'Unidentified',
    condition:
      'Intact and Visible but the control point number cannot be identified',
    imageUrl: '/images/Picture8.jpg',
  },
  {
    id: 9,
    number: 'BBM 37',
    type: 'BBM',
    barangay: 'Poblacion and Iraya',
    status: 'Intact',
    latitude: 13.190686,
    longitude: 123.600964,
    description:
      'Located at the intersection in front of Centro Guinobatan Museum and Abordo Trading building',
    remarks: 'Intact',
    condition: 'Intact and Visible. The control point number is identified',
    imageUrl: '/images/Picture9.jpg',
  },
  {
    id: 10,
    number: 'BLLM 153',
    type: 'BLLM',
    barangay: 'Iraya',
    status: 'Intact',
    latitude: 13.189519,
    longitude: 123.602017,
    description: 'At the Barangay Hall building of barangay Iraya, Guinobatan',
    remarks: 'Intact',
    condition:
      'The control point is intact, visible, and well-maintained with little to no signs of tarnishing or any severe destruction',
    imageUrl: '/images/Picture10.jpg',
  },
  {
    id: 11,
    number: 'BBM 34',
    type: 'BBM',
    barangay: 'Ilawod',
    status: 'Intact',
    latitude: 13.190753,
    longitude: 123.598378,
    description:
      'Located on the left side of Osurman Trading building in barangay Ilawod',
    remarks: 'Intact',
    condition:
      'The GCP is intact with little to no signs of tarnishing or any severe destruction',
    imageUrl: '/images/Picture11.jpg',
  },
  {
    id: 12,
    number: 'BBM 47',
    type: 'BBM',
    barangay: 'Inamnan Pequeño',
    status: 'Intact',
    latitude: 13.188075,
    longitude: 123.601481,
    description: 'Near Inamnan Pequeño Caltex and Crispy King',
    remarks: 'Intact',
    condition:
      'The GCP is intact and has no signs of any severe dislocation or destruction',
    imageUrl: '/images/Picture12.jpg',
  },
  {
    id: 13,
    number: 'BBM 48',
    type: 'BBM',
    barangay: 'Iraya and Inamnan Pequeño',
    status: 'Disturbed',
    latitude: 13.188333,
    longitude: 123.601111,
    description: 'Located on the side of Caltex in barangay Iraya',
    remarks: 'Disturbed',
    condition:
      'The GCP is no longer attached to the ground and can be easily moved or displaced',
    imageUrl: '/images/Picture13.jpg',
  },
  {
    id: 14,
    number: 'BBM 1',
    type: 'BBM',
    barangay: 'Iraya',
    status: 'Disturbed',
    latitude: 13.190569,
    longitude: 123.601339,
    description: 'IDK si barangay',
    remarks: 'Disturbed',
    condition: 'The GCP appears to be no longer attached to the ground',
    imageUrl: '/images/Picture14.jpg',
  },
  {
    id: 15,
    number: 'BBM 35',
    type: 'BBM',
    barangay: 'Iraya, Poblacion, and Inamnan Pequeño',
    status: 'Disturbed',
    latitude: 13.189019,
    longitude: 123.600792,
    description: 'Outside Guinobatan Wet market, in front of Dan-Ke Trading',
    remarks: 'Disturbed',
    condition: 'The GCP is moved from its original position',
    imageUrl: '/images/Picture15.jpg',
  },
  {
    id: 16,
    number: 'BLLM 154',
    type: 'BLLM',
    barangay: 'Poblacion',
    status: 'Undisturbed',
    latitude: 13.189686,
    longitude: 123.602786,
    description:
      'Located on the sidewalk of Guinobatan East Central School in front of the Motortrade building',
    remarks: 'Undisturbed',
    condition:
      'The GCP is intact and has no signs of any severe dislocation or destruction',
    imageUrl: '/images/Picture16.jpg',
  },
  {
    id: 17,
    number: 'BBM 50',
    type: 'BBM',
    barangay: 'Poblacion',
    status: 'Intact',
    latitude: 13.191272,
    longitude: 123.597622,
    description:
      'Side of Guino West Central School and in front of Bicol University College of Agriculture and Forestry (BUCAF)',
    remarks: 'Intact and visible',
    condition:
      'The GCP is intact and has no signs of any severe dislocation or destruction',
    imageUrl: '/images/Picture17.jpg',
  },
  {
    id: 18,
    number: 'BLLM UNKNOWN',
    type: 'BLLM',
    barangay: 'Ilawod',
    status: 'Unidentified',
    latitude: 13.194103,
    longitude: 123.596811,
    description: 'In front of Nuestra Señora Funeral Home',
    remarks: 'Unidentified',
    condition: 'Intact on the ground but control number cannot be identified',
    imageUrl: '/images/Picture18.jpg',
  },
  {
    id: 19,
    number: 'BBM 50',
    type: 'BBM',
    barangay: 'Calzada',
    status: 'Intact',
    latitude: 13.188258,
    longitude: 123.596656,
    description: 'Near MCGI',
    remarks: 'Intact',
    condition:
      'The GCP is intact with little to no signs of tarnishing or any severe destruction',
    imageUrl: '/images/Picture19.jpg',
  },
  {
    id: 20,
    number: 'BLLM 80',
    type: 'BLLM',
    barangay: 'Inamnan Grande',
    status: 'Intact',
    latitude: 13.188622,
    longitude: 123.598747,
    description: 'On the side of the road near the entrance to Morga Hills',
    remarks: 'Intact',
    condition:
      'The GCP is intact with minimal signs of tarnishing and chipped edges',
    imageUrl: '/images/Picture20.jpg',
  },
  {
    id: 21,
    number: 'BBM UNK',
    type: 'BBM',
    barangay: 'Calzada',
    status: 'Disturbed',
    latitude: 13.190242,
    longitude: 123.598839,
    description: 'On the side of a drainage near a gray house',
    remarks: 'Disturbed',
    condition:
      'Intact on the ground and tilted. Control number cannot be identified',
    imageUrl: '/images/Picture21.jpg',
  },
  {
    id: 22,
    number: 'GCP UNKNOWN',
    type: 'Unknown',
    barangay: 'Calzada',
    status: 'Unidentified',
    latitude: 13.190678,
    longitude: 123.598403,
    description:
      'In front of Osurman Trading, other side of the road from BBM No. 34',
    remarks: 'Unidentified',
    condition: 'Unknown GCP',
    imageUrl: '/images/Picture22.jpg',
  },
  {
    id: 23,
    number: 'BBM UNKNOWN',
    type: 'BBM',
    barangay: 'Inamnan Grande',
    status: 'Intact',
    latitude: 13.188461,
    longitude: 123.597683,
    description: 'Located on an intersection near Flash express hub',
    remarks: 'Intact',
    condition:
      'Intact on the ground with little to no signs of tarnishing or any severe destruction, but control number cannot be identified',
    imageUrl: '/images/Picture23.jpg',
  },
];

export const barangaysList = [
  'Calzada',
  'Ilawod',
  'Inamnan Grande',
  'Inamnan Pequeño',
  'Iraya',
  'Poblacion',
];
